name: Build and Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Create ZIP file
      run: |
        COMMIT_ID=$(git rev-parse --short HEAD)
        ZIP_NAME="PvP For Cuties ${{ github.ref_name }}.zip"
        echo "ZIP_NAME=${ZIP_NAME}" >> $GITHUB_ENV
        zip -r "${ZIP_NAME}" . -x ".git/*" ".github/*"
        echo "${ZIP_NAME}"
    - name: Upload ZIP artifact
      uses: actions/upload-artifact@v4
      with:
        name: resource-pack-artifact
        path: ${{ env.ZIP_NAME }}
    - name: Read changelog file
      id: read-changelog
      run: |
        CHANGELOG=$(cat CHANGELOG.md)
        CHANGELOG="${CHANGELOG//'%0A'/$'\n'}"
        CHANGELOG="${CHANGELOG//'%0D'/$'\r'}"
        CHANGELOG="${CHANGELOG//'%25'/'%'}"
        echo "DECODED_CHANGELOG<<EOF" >> $GITHUB_OUTPUT
        echo "$CHANGELOG" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ${{ steps.read-changelog.outputs.DECODED_CHANGELOG }}
          Automated release created by GitHub Actions
        draft: false
        prerelease: false
    - name: Upload Release Artifact
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: "${{ env.ZIP_NAME }}"
        asset_name: "${{ env.ZIP_NAME }}"
        asset_content_type: application/zip
    - name: Upload to Modrinth
      uses: cloudnode-pro/modrinth-publish@v2
      with:
        project: iQx2ijVe
        version: ${{ github.ref_name }}
        loaders: '["minecraft"]'
        game-versions: '["1.21.x","25w31a"]'
        files: '${{ env.ZIP_NAME }}'
        token: ${{ secrets.MODRINTH}}
        changelog: ${{ steps.read-changelog.outputs.DECODED_CHANGELOG }}
    - name: "Actions for Discord"
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_USERNAME: "PvP for Cuties"
        DISCORD_AVATAR: https://cdn.modrinth.com/data/iQx2ijVe/29eddb9ed69325732b1280f295c35428b3f8115f_96.webp
        DISCORD_MENTIONS: >-
          {
            "allowed_mentions": {
              "roles": ["1325604992484376688"]
            }
          }

      uses: Ilshidur/action-discord@0.4.0
      with:
        args: "<@&1325604992484376688>\n${{ steps.read-changelog.outputs.DECODED_CHANGELOG }}\nDownload: https://modrinth.com/resourcepack/pvp-for-cuties/version/${{ github.ref_name }}"